services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: clouddb
      MYSQL_ROOT_PASSWORD: your-db-password
  api:
    image: arkcloudstorage/api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DATABASE_URL: mysql://root:your-db-password@db:3306/clouddb
      REGISTER_CLUSTERS: your-cluster-name:your-cluster-secret
volumes:
  data:

